=== Mikulitch/XML-Parser/src/main/resources/Gems_scheme.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">

<element name = "gems">
	<complexType>
		<sequence>
			<element name = "gem">
				<complexType>
					<sequence>
						<element name="id" type="int"/>
						<element name="name" type="string"/>
						<element name="preciousness" type="string"/>
						<element name="origin" type="string"/>
						<element name="visualParameters" >
							<complexType>
								<sequence>
									<element name="color" type="string"/>
									<element name="transparency" type="int"/>
									<element name="facets" type="string"/>
								</sequence>
							</complexType>
						</element>
						<element name="value" type="string"/>
					</sequence>
				</complexType>
		
			</element>
		
		</sequence>
		<attribute name = "id"  use= "required"/>
	</complexType>
	
</element>
</schema>

=== Mikulitch/XML-Parser/src/main/resources/uploads/Gems.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/gems"
         xsi:schemaLocation="http://www.example.com/gems Gems_scheme.xsd">
    <gem>
        <id>1</id>
		<name>Алмаз</name>
		<preciousness>Драгоценный</preciousness>
		<origin>Россия, Австралия, Канада, Бразилия, ЮАР</origin>
		<visualParameters>
			<color>Безцветный</color>
			<transparency>70</transparency>
			<facets>2-102</facets>
		</visualParameters>
		<value>1-530</value>
    </gem>
     <gem>
        <id>2</id>
		<name>Изумруд</name>
		<preciousness>Драгоценный</preciousness>
		<origin>Россия</origin>
		<visualParameters>
			<color>Зеленый</color>
			<transparency>67</transparency>
			<facets>2-98</facets>
		</visualParameters>
		<value>950</value>
    </gem>
	 <gem>
        <id>3</id>
		<name>Сапфир</name>
		<preciousness>Драгоценный</preciousness>
		<origin>Россия, Китай</origin>
		<visualParameters>
			<color>Синий</color>
			<transparency>67</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>590</value>
    </gem>
	 <gem>
        <id>4</id>
		<name>Рубин</name>
		<preciousness>Драгоценный</preciousness>
		<origin>Россия</origin>
		<visualParameters>
			<color>Красный</color>
			<transparency>69</transparency>
			<facets>2-68</facets>
		</visualParameters>
		<value>780</value>
    </gem>
	 <gem>
        <id>5</id>
		<name>Александрит</name>
		<preciousness>Драгоценный</preciousness>
		<origin>США</origin>
		<visualParameters>
			<color>Фиолетовый</color>
			<transparency>60</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>450</value>
    </gem>
	 <gem>
        <id>6</id>
		<name>Аместист</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Россия</origin>
		<visualParameters>
			<color>Фиолетовый</color>
			<transparency>57</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>340</value>
    </gem>
	 <gem>
        <id>7</id>
		<name>Аквамарин</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Бразилия</origin>
		<visualParameters>
			<color>Голубой</color>
			<transparency>56</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>780</value>
    </gem>
	<gem>
        <id>8</id>
		<name>Гранат</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Россия, Бразилия</origin>
		<visualParameters>
			<color>Красный</color>
			<transparency>59</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>1002</value>
    </gem>
	 <gem>
        <id>9</id>
		<name>Горный хрусталь</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Россия, Китай</origin>
		<visualParameters>
			<color>Безцветный</color>
			<transparency>40</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>970</value>
    </gem>
	 <gem>
        <id>10</id>
		<name>Топаз</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Бразилия, США</origin>
		<visualParameters>
			<color>Голубой</color>
			<transparency>58</transparency>
			<facets>2-58</facets>
		</visualParameters>
		<value>670</value>
    </gem>
	
	   

</gems>
